"use strict";

const category = require("../models/category");
const season = require("../models/season");

/** @type {import('sequelize-cli').Migration} */
module.exports = {
	async up(queryInterface, Sequelize) {
		/**
		 * building, season, and location are nullable
     * buildings:{6:pierres}
		 * categories: {1:artisan goods, 2:recipes, 3:foraging, 4:fishes, 5:minerals, 6:crops,
     *              7:trees, 8:books, 9:animals, 10:trinkets, 11:resources, 12:trash,
     *              13:special, 14:ingredients, 15:monster loot}
		 * locations: {1: town, 2: cindersap, 3: beach, 4: mountain, 5:witches swamp, 6: farm,
     *             7:desert, 8:ginger island, 9: sewers}
		 * seasons: {1: Spring, 2:summer, 3: fall, 4: winter, 5: year-round}
     * I made ingredients only for pierre's, add to farm in later implementation
      // { name:'Red Mushroom', categoryId: 3, seasonId: 2 , buildingId: 11 }
          - red mushroom and purple mushroom are found in different seasons/locations, but year round in the mines (level 81) - for simplicity, I'm choosing year-round in mountains / mines
          - cactus fruit can be foraged and farmed, but only labeling it as foragable from desert
          - any fish found in river and town will be classified under forest
          - any fish found in river (town) will be classfied under Pelican Town
          - midnight carp found in fall,winter and year-round on ginger island - only adding year round/ginger island
          - not including legendary fish I and II
          - geode minerals will be added later - need to implment id for magma geode, geode, omni geode
          - not adding frozen geode - need subcategory for geodes
          - add universal gifts
          *FIXME - Check each line and make sure it has the right fields, nullable and non-nullable
          *FIXME - Check relationship on gifts to seasons, a gift can belong to many seasons, and a season can belong to many gifts
          */
		return queryInterface.bulkInsert("Gifts", [
			{ id: 1, name: "Honey" },
			{ id: 2, name: "Wine" },
			{ id: 3, name: "Pale Ale" },
			{ id: 4, name: "Beer" },
			{ id: 5, name: "Cheese" },
			{ id: 6, name: "Goat Cheese" },
			{ id: 7, name: "Mead" },
			{ id: 8, name: "Coffee" },
			{ id: 9, name: "Green Tea" },
			{ id: 10, name: "Juice" },
			{ id: 11, name: "Cloth" },
			{ id: 12, name: "Dinosaur Mayonnaise" },
			{ id: 13, name: "Duck Mayonnaise" },
			{ id: 14, name: "Mayonnaise" },
			{ id: 15, name: "Void Mayonnaise" },
			{ id: 16, name: "Truffle Oil" },
			{ id: 17, name: "Oil" },
			{ id: 18, name: "Wheat Flour" },
			{ id: 19, name: "Sugar" },
			{ id: 20, name: "Rice" },
			{ id: 21, name: "Vinegar" },
			{ id: 22, name: "Aged Roe" },
			{ id: 23, name: "Caviar" },
			{ id: 24, name: "Jelly" },
			{ id: 25, name: "Pickle" },
			{ id: 26, name: "Smoked Fish" },
			{ id: 27, name: "Dried Mushroom" },
			{ id: 28, name: "Dried Fruit" },
			{ id: 29, name: "Raisin" },
			{ id: 30, name: "Maple Syrup" },
			{ id: 31, name: "Oak Resin" },
			{ id: 32, name: "Pine Tar" },
			{ id: 33, name: "Mystic Syrup" },
			{ id: 34, name: "Fried Egg" },
			{ id: 35, name: "Omelet" },
			{ id: 36, name: "Salad" },
			{ id: 37, name: "Cheese Cauliflower" },
			{ id: 38, name: "Baked Fish" },
			{ id: 39, name: "Parsnip Soup" },
			{ id: 40, name: "Vegetable Medley" },
			{ id: 41, name: "Complete Breakfast" },
			{ id: 42, name: "Fried Calamari" },
			{ id: 43, name: "Strange Bun" },
			{ id: 44, name: "Lucky Lunch" },
			{ id: 45, name: "Fried Mushroom" },
			{ id: 46, name: "Pizza" },
			{ id: 47, name: "Bean Hotpot" },
			{ id: 48, name: "Glazed Yams" },
			{ id: 49, name: "Carp Surprise" },
			{ id: 50, name: "Hashbrowns" },
			{ id: 51, name: "Pancakes" },
			{ id: 52, name: "Salmon Dinner" },
			{ id: 53, name: "Blueberry Tart" },
			{ id: 54, name: "Super Meal" },
			{ id: 55, name: "Stuffing" },
			{ id: 56, name: "Fish Taco" },
			{ id: 57, name: "Crispy Bass" },
			{ id: 58, name: "Pepper Poppers" },
			{ id: 59, name: "Bread" },
			{ id: 60, name: "Tom Kha Soup" },
			{ id: 61, name: "Trout Soup" },
			{ id: 62, name: "Chocolate Cake" },
			{ id: 63, name: "Pink Cake" },
			{ id: 64, name: "Rhubarb Pie" },
			{ id: 65, name: "Cookie" },
			{ id: 66, name: "Spaghetti" },
			{ id: 67, name: "Fried Eel" },
			{ id: 68, name: "Spicy Eel" },
			{ id: 69, name: "Sashimi" },
			{ id: 70, name: "Maki Roll" },
			{ id: 71, name: "Tortilla" },
			{ id: 72, name: "Red Plate" },
			{ id: 73, name: "Eggplant Parmesan" },
			{ id: 74, name: "Rice Pudding" },
			{ id: 75, name: "Ice Cream" },
			{ id: 76, name: "Autumn's Bounty" },
			{ id: 77, name: "Pumpkin Soup" },
			{ id: 78, name: "Cranberry Sauce" },
			{ id: 79, name: "Farmer's Lunch" },
			{ id: 80, name: "Survival Burger" },
			{ id: 81, name: "Dish O' The Sea" },
			{ id: 82, name: "Miner's Treat" },
			{ id: 83, name: "Roots Platter" },
			{ id: 84, name: "Triple Shot Espresso" },
			{ id: 85, name: "Seafoam Pudding" },
			{ id: 86, name: "Algae Soup" },
			{ id: 87, name: "Pale Broth" },
			{ id: 88, name: "Plum Pudding" },
			{ id: 89, name: "Artichoke Dip" },
			{ id: 90, name: "Stir Fry" },
			{ id: 91, name: "Roasted Hazelnuts" },
			{ id: 92, name: "Pumpkin Pie" },
			{ id: 93, name: "Radish Salad" },
			{ id: 94, name: "Fruit Salad" },
			{ id: 95, name: "Blackberry Cobbler" },
			{ id: 96, name: "Cranberry Candy" },
			{ id: 97, name: "Bruschetta" },
			{ id: 98, name: "Coleslaw" },
			{ id: 99, name: "Fiddlehead Risotto" },
			{ id: 100, name: "Poppyseed Muffin" },
			{ id: 101, name: "Chowder" },
			{ id: 102, name: "Fish Stew" },
			{ id: 103, name: "Escargot" },
			{ id: 104, name: "Lobster Bisque" },
			{ id: 105, name: "Maple Bar" },
			{ id: 106, name: "Crab Cakes" },
			{ id: 107, name: "Shrimp Cocktail" },
			{ id: 108, name: "Ginger Ale" },
			{ id: 109, name: "Banana Pudding" },
			{ id: 110, name: "Mango Sticky Rice" },
			{ id: 111, name: "Poi" },
			{ id: 112, name: "Tropical Curry" },
			{ id: 113, name: "Squid Ink Ravioli" },
			{ id: 114, name: "Moss Soup" },
			{ id: 115, name: "Sap" },
			{ id: 116, name: "Common Mushroom" },
			{ id: 117, name: "Daffodil" },
			{ id: 118, name: "Dandelion" },
			{ id: 119, name: "Leek" },
			{ id: 120, name: "Morel" },
			{ id: 121, name: "Salmonberry" },
			{ id: 122, name: "Spring Onion" },
			{ id: 123, name: "Wild Horseradish" },
			{ id: 124, name: "Fiddlehead Fern" },
			{ id: 125, name: "Spicy Berry" },
			{ id: 126, name: "Sweet Pea" },
			{ id: 127, name: "Rainbow Shell" },
			{ id: 128, name: "Blackberry" },
			{ id: 129, name: "Chanterelle" },
			{ id: 130, name: "Hazelnut" },
			{ id: 131, name: "Wild Plum" },
			{ id: 132, name: "Crocus" },
			{ id: 133, name: "Crystal Fruit" },
			{ id: 134, name: "Holly" },
			{ id: 135, name: "Snow Yam" },
			{ id: 136, name: "Winter Root" },
			{ id: 137, name: "Nautilus Shell" },
			{ id: 138, name: "Clam" },
			{ id: 139, name: "Cockle" },
			{ id: 140, name: "Coral" },
			{ id: 141, name: "Mussel" },
			{ id: 142, name: "Oyster" },
			{ id: 143, name: "Sea Urchin" },
			{ id: 144, name: "Seaweed" },
			{ id: 145, name: "Cave Carrot" },
			{ id: 146, name: "Red Mushroom" },
			{ id: 147, name: "Purple Mushroom" },
			{ id: 148, name: "Cactus Fruit" },
			{ id: 149, name: "Coconut" },
			{ id: 150, name: "Ginger" },
			{ id: 151, name: "Magma Cap" },
			{ id: 152, name: "Smallmouth Bass" },
			{ id: 153, name: "Pike" },
			{ id: 154, name: "Wallaye" },
			{ id: 155, name: "Perch" },
			{ id: 156, name: "Salmon" },
			{ id: 157, name: "Lingcod" },
			{ id: 158, name: "Catfish" },
			{ id: 159, name: "Rainbow Trout" },
			{ id: 160, name: "Dorado" },
			{ id: 161, name: "Chub" },
			{ id: 162, name: "Goby" },
			{ id: 163, name: "Bream" },
			{ id: 164, name: "Sunfish" },
			{ id: 165, name: "Tiger Trout" },
			{ id: 166, name: "Shad" },
			{ id: 167, name: "Woodskip" },
			{ id: 168, name: "Sea Cucumber" },
			{ id: 169, name: "Albacore" },
			{ id: 170, name: "Anchovy" },
			{ id: 171, name: "Tilapia" },
			{ id: 172, name: "Sardine" },
			{ id: 173, name: "Red Mullet" },
			{ id: 174, name: "Herring" },
			{ id: 175, name: "Eel" },
			{ id: 176, name: "Red Snapper" },
			{ id: 177, name: "Squid" },
			{ id: 178, name: "Halibut" },
			{ id: 179, name: "Pufferfish" },
			{ id: 180, name: "Tuna" },
			{ id: 181, name: "Octopus" },
			{ id: 182, name: "Super Cucumber" },
			{ id: 183, name: "Flounder" },
			{ id: 184, name: "Bullhead" },
			{ id: 185, name: "Sturgeon" },
			{ id: 186, name: "Ice Pip" },
			{ id: 187, name: "Lava Eel" },
			{ id: 188, name: "Largemouth Bass" },
			{ id: 189, name: "Carp" },
			{ id: 190, name: "Void Salmon" },
			{ id: 191, name: "Sandfish" },
			{ id: 192, name: "Stonefish" },
			{ id: 193, name: "Scorpion Carp" },
			{ id: 194, name: "Ghostfish" },
			{ id: 195, name: "Lionfish" },
			{ id: 196, name: "Blue Discus" },
			{ id: 197, name: "Midnight Carp" },
			{ id: 198, name: "Stingray" },
			{ id: 199, name: "Slimejack" },
			{ id: 200, name: "Amethyst" },
			{ id: 201, name: "Aquamarine" },
			{ id: 202, name: "Diamond" },
			{ id: 203, name: "Emerald" },
			{ id: 204, name: "Jade" },
			{ id: 205, name: "Prismatic Shard" },
			{ id: 206, name: "Ruby" },
			{ id: 207, name: "Topaz" },
			{ id: 208, name: "Earth Crystal" },
			{ id: 209, name: "Fire Quartz" },
			{ id: 210, name: "Frozen Tear" },
			{ id: 211, name: "Quartz" },
			{ id: 212, name: "Blue Jazz" },
			{ id: 213, name: "Carrot" },
			{ id: 214, name: "Cauliflower" },
			{ id: 215, name: "Coffee Bean" },
			{ id: 216, name: "Garlic" },
			{ id: 217, name: "Green Bean" },
			{ id: 218, name: "Kale" },
			{ id: 219, name: "Parsnip" },
			{ id: 220, name: "Potato" },
			{ id: 221, name: "Rhubarb" },
			{ id: 222, name: "Strawberry" },
			{ id: 223, name: "Tulip" },
			{ id: 224, name: "Unmilled Rice" },
			{ id: 225, name: "Ancient Fruit" },
			{ id: 226, name: "Spring Seeds" },
			{ id: 227, name: "Blueberry" },
			{ id: 228, name: "Corn" },
			{ id: 229, name: "Hops" },
			{ id: 230, name: "Hot Pepper" },
			{ id: 231, name: "Melon" },
			{ id: 232, name: "Poppy" },
			{ id: 233, name: "Radish" },
			{ id: 234, name: "Red Cabbage" },
			{ id: 235, name: "Starfruit" },
			{ id: 236, name: "Summer Spangle" },
			{ id: 237, name: "Summer Squash" },
			{ id: 238, name: "Sunflower" },
			{ id: 239, name: "Tomato" },
			{ id: 240, name: "Wheat" },
			{ id: 241, name: "Pineapple" },
			{ id: 242, name: "Taro Root" },
			{ id: 243, name: "Summer Seeds" },
			{ id: 244, name: "Amaranth" },
			{ id: 245, name: "Artichoke" },
			{ id: 246, name: "Beet" },
			{ id: 247, name: "Bok Choy" },
			{ id: 248, name: "Broccoli" },
			{ id: 249, name: "Cranberries" },
			{ id: 250, name: "Eggplant" },
			{ id: 251, name: "Fairy Rose" },
			{ id: 252, name: "Grape" },
			{ id: 253, name: "Pumpkin" },
			{ id: 254, name: "Yam" },
			{ id: 255, name: "Fall Seeds" },
			{ id: 256, name: "Powdermelon" },
			{ id: 257, name: "Winter Seeds" },
			{ id: 258, name: "Fiber" },
			{ id: 259, name: "Mixed Flower Seeds" },
			{ id: 260, name: "Mixed Seeds" },
			{ id: 261, name: "Apple" },
			{ id: 262, name: "Apricot" },
			{ id: 263, name: "Banana" },
			{ id: 264, name: "Cherry" },
			{ id: 265, name: "Mango" },
			{ id: 266, name: "Orange" },
			{ id: 267, name: "Peach" },
			{ id: 268, name: "Pomegranate" },
			{ id: 269, name: "Dinosaur Egg" },
			{ id: 270, name: "Duck Egg" },
			{ id: 271, name: "Duck Feather" },
			{ id: 272, name: "Egg" },
			{ id: 273, name: "Goat Milk" },
			{ id: 274, name: "Milk" },
			{ id: 275, name: "Field Snack" },
			{ id: 276, name: "Tea Leaves" },
			{ id: 277, name: "Gold Bar" },
			{ id: 278, name: "Iridium Bar" },
			{ id: 279, name: "Omni Geode" },
			{ id: 280, name: "Copper Bar" },
			{ id: 281, name: "Iron Bar" },
			{ id: 282, name: "Coal" },
			{ id: 283, name: "Gold Ore" },
			{ id: 284, name: "Iridium Ore" },
			{ id: 285, name: "Refined Quartz" },
			{ id: 286, name: "Lemon Stone" },
			{ id: 287, name: "Solar Essence" },
			{ id: 288, name: "Void Essence" },
			{ id: 289, name: "Wool" },
			{ id: 290, name: "Lobster" }, //290
			{ id: 291, name: "Squid Ink" },
			{ id: 292, name: "Clay" },
			{ id: 293, name: "Truffle" }, //293
			{ id: 294, name: "Large Goat Milk" },
			{ id: 295, name: "Golden Pumpkin" },
			{ id: 296, name: "Magic Rock Candy" },
			{ id: 297, name: "Pearl" },
			{ id: 298, name: "Rabbit's Foot" },
			{ id: 299, name: "Stardrop Tea" }, //299
			{ id: 300, name: "Pina Colada" },
			{ id: 301, name: "Sweet Gem Berry" },
			{ id: 302, name: "Large Milk" },
			{ id: 303, name: "Driftwood" },
			{ id: 304, name: "Void Egg" },
			{ id: 305, name: "Jack-O-Latern" },
			{ id: 306, name: "Green Algae" }, //306
			{ id: 307, name: "White Algae" },
			{ id: 308, name: "Spice Berry" }, //307
			{ id: 309, name: "Joja Cola" }, //308
			{ id: 310, name: "Frog Egg" },
			{ id: 311, name: "Snail" }, //311
			{ id: 312, name: "Pearl" },
			{ id: 313, name: "Monster Compendium" },
			{ id: 314, name: "Monster Musk" }, //314
			{ id: 315, name: "Life Elixir" },
			{ id: 316, name: "Treasure Chest" }, //316
			{ id: 317, name: "Dried Mushrooms" }, //317
			{ id: 318, name: "Dried Fruit" }, //318
			{ id: 319, name: "Raisins" }, //319
			{ id: 320, name: "Roe" },
			{ id: 321, name: "Qi Fruit" }, //321
			{ id: 322, name: "Ostrich Egg" },
			{ id: 323, name: "Parrot Egg" },
			{ id: 324, name: "Dragon Tooth" }, //324
			{ id: 325, name: "Wild Bait" }, //325
		]);
	},

	async down(queryInterface, Sequelize) {
		/**
		 * Add commands to revert seed here.
		 *
		 * Example:
		 * await queryInterface.bulkDelete('People', null, {});
		 */
		await queryInterface.bulkDelete("Villager_Gifts", null, {});
		await queryInterface.bulkDelete("Gift_Categories", null, {});
		return queryInterface.bulkDelete("Gifts", null, {});
	},
};
